#include <linux/module.h>
#include <linux/slab.h>
#include <linux/cdev.h>
#include <linux/fs.h>
#include <linux/uaccess.h>
#include <linux/workqueue.h>
#include <linux/string.h> 
#include <linux/usb/cdc.h> 

#include <linux/kthread.h>

//  
// AI Statement: This code was originated by Roger D. Pease. It was not generated by prompts. 
//    AI (Junie with qwen3-coder) was used for analysis, bug detection, and minor fixes/updates. 
//
// Please feel free to quiz me on the code and why certain decisions were made. 
// 


#include <linux/usb.h> 

#define DRIVER_NAME "my_usb_driver"
#define DEVICE_NAME "my_usb_device"

#define USB_SKEL_VENDOR_ID  (0xaaaa)
#define USB_SKEL_PRODUCT_ID (0x0c0c)

#define COMMAND_LEN        (64)
#define RESULT_BUFFER_LEN  (256)



//
// This is a structure for each *device*. A device is the thing you plug the USB cable into.
//

typedef struct {

    struct usb_device *dev;

    struct device *my_char_device;
    int char_minor_device;
    struct list_head node; // Tie-in for my_usb_devices_list
    struct list_head filehandles;

} my_usb_device_t;

// 
// This is for each filehandle, which is what you .open,.read,.write and .close.  
//

typedef struct { 

    int minor_device;

    char rbuffer[RESULT_BUFFER_LEN];
    int rbeginindex;
    int rendindex;
    struct list_head node; // Tie-in to my_usb_device_t->filehandles
    struct file *filp;
    my_usb_device_t * my_usb_device; // USB Device tied to this filehandle.
    int char_minor_device;
 
} my_fh_private_data_t;

//
// Global structure for all items. 
//

typedef struct
{

    spinlock_t lock;
    struct class *my_class;
    int major_number;
    struct list_head my_usb_devices_list;
    unsigned long minor_map;

} my_usb_driver_t;

my_usb_driver_t * my_usb_driver;

int setup_char_driver(my_usb_device_t * my_usb_device);
void destroy_char_driver(my_usb_device_t * my_usb_device);
static int char_file_open(struct inode *inode, struct file *filp);
ssize_t char_file_read(struct file *filp, char * buf, size_t byteCount, loff_t * byteOffset);
ssize_t char_file_write (struct file *filp,const char * buf, size_t byteCount, loff_t * byteOffset);

static struct usb_device_id my_usb_table [] = {
        { USB_DEVICE(USB_SKEL_VENDOR_ID, USB_SKEL_PRODUCT_ID) },
        { }                      /* Terminating entry */
};

MODULE_DEVICE_TABLE (usb, my_usb_table);

////////////////////////////////////////////////////////////////
//
// Called when a USB device is plugged in.
//

static int my_usb_probe(struct usb_interface *interface, const struct usb_device_id *id) 
{
    my_usb_device_t *my_usb_device;
    struct usb_device *dev = interface_to_usbdev(interface);

    if ((id->idVendor  != USB_SKEL_VENDOR_ID) || (id->idProduct != USB_SKEL_PRODUCT_ID))
    {
        return -EINVAL;
    }

    my_usb_device = kzalloc(sizeof(my_usb_device_t), GFP_KERNEL);

    if (my_usb_device == NULL)
    {
        return -ENOMEM;
    }

    my_usb_device->dev = dev;

    INIT_LIST_HEAD(&my_usb_device->filehandles); 

    int result = setup_char_driver(my_usb_device);
    if (result < 0)
    {
       kfree(my_usb_device);
       pr_err("Could not set up char driver.");
       return result;
    }

    struct usb_host_interface *iface_desc;
    struct usb_endpoint_descriptor *epd;
    unsigned int i;

    iface_desc = interface->cur_altsetting;

    for (i = 0; i < iface_desc->desc.bNumEndpoints; ++i) {
  
        epd = &iface_desc->endpoint[i].desc;

        char *dir = NULL ;
        if (usb_endpoint_dir_in(epd))      { dir = "IN";  }
        if (usb_endpoint_dir_out(epd))     { dir = "OUT"; }

        char *type = "undefined";
        if (usb_endpoint_xfer_control(epd)) type = "ctrl";
        if (usb_endpoint_xfer_bulk(epd))    type = "bulk";
        if (usb_endpoint_xfer_isoc(epd))    type = "isoc";
        if (usb_endpoint_xfer_int(epd))     type = "int";

        pr_info(DRIVER_NAME "  Endpoint %d %s %s",i,type,dir);
        pr_info(DRIVER_NAME "   bLength %d  bDescriptorType %d",epd->bLength,epd->bDescriptorType);
        pr_info(DRIVER_NAME "   bEndpointAddress %d bmAttributes %d wMaxPacketSize %d", epd->bEndpointAddress,  epd->bmAttributes,  epd->wMaxPacketSize);
              
    }

    usb_set_intfdata(interface, my_usb_device);

    spin_lock(&my_usb_driver->lock);
    list_add(&my_usb_device->node, &my_usb_driver->my_usb_devices_list);
    spin_unlock(&my_usb_driver->lock);
 
    return 0;
 
}

// Gets called when user application calls os.open

static int char_file_open(struct inode *inode, struct file *filp)
{
    my_fh_private_data_t * my_fh_private_data;

    my_fh_private_data = (my_fh_private_data_t *) kzalloc(sizeof(my_fh_private_data_t),GFP_KERNEL);

    if (my_fh_private_data == NULL)
    {
        return -ENOMEM;
    }

    my_fh_private_data->char_minor_device = iminor(inode);

    my_usb_device_t * my_usb_device;

    list_for_each_entry(my_usb_device, &my_usb_driver->my_usb_devices_list, node)
    {
        if (my_usb_device->char_minor_device == my_fh_private_data->char_minor_device)
        {
            my_fh_private_data->my_usb_device = my_usb_device;
            break;
        }
    }

    if (my_fh_private_data->my_usb_device == NULL)
    {
        pr_err("char_file_open: Could not find my_usb_device for char_minor_device %d\n", my_fh_private_data->char_minor_device);
        return -ENODEV;
    }

    pr_info("char_file_open: my_usb_device->dev = %p\n", my_usb_device->dev);

    filp->private_data = (void *) my_fh_private_data;

    return 0;

}

// Gets called when user application calls os.close 

static int char_file_close(struct inode *inode, struct file *filp)
{
    kfree(filp->private_data);
    return 0;
}


//
// Gets called when user application calls os.read() from a system device they opened. 
// However there is no guarantee a specific call will read the whole available data,
// so we need to check if we have written all the data.
//
ssize_t char_file_read(struct file *filp, char * buf, size_t byteCount, loff_t * byteOffset)
{
    my_fh_private_data_t * my_fh_private_data = filp->private_data;
    int bytes_written_this_call = 0; 
    char c; 

    // Locking should probably be per-device if we want to be safe, but for now let's fix the basic issues.
    spin_lock(&my_usb_driver->lock);

    while ((bytes_written_this_call < byteCount) && (my_fh_private_data->rbeginindex != my_fh_private_data->rendindex))
    {

        c = my_fh_private_data->rbuffer[my_fh_private_data->rbeginindex++];
        if (my_fh_private_data->rbeginindex == RESULT_BUFFER_LEN) my_fh_private_data->rbeginindex = 0;
        if (put_user(c,buf + bytes_written_this_call)) {
            spin_unlock(&my_usb_driver->lock);
            return -EFAULT;
        }
        bytes_written_this_call++;
        pr_info(DRIVER_NAME " Wrote %d ",(u8) c);

    }  

    *byteOffset += bytes_written_this_call;
    pr_info(DRIVER_NAME " char_file_read() ended %d bytes written",bytes_written_this_call);

    spin_unlock(&my_usb_driver->lock);

    return bytes_written_this_call; 
    
}

//
// Gets called when user application calls os.write(). 
// This is where we issue commands to the device. 
// byteOffset is essentially a 'reminder' pointer in case a write happens at multiple points. 
//

ssize_t char_file_write (struct file *filp, const char * buf, size_t byteCount, loff_t * byte_offset)
{
    my_fh_private_data_t * my_fh_private_data = filp->private_data;
    my_usb_device_t *my_usb_device;
    ssize_t bytes_written = 0; 
    char command_buffer[COMMAND_LEN]; 

    spin_lock(&my_usb_driver->lock);

    if (list_empty(&my_usb_driver->my_usb_devices_list)) {
        spin_unlock(&my_usb_driver->lock);
        return -ENODEV;
    }

    my_usb_device = list_first_entry(&my_usb_driver->my_usb_devices_list, my_usb_device_t, node);
    spin_unlock(&my_usb_driver->lock);

    memset(command_buffer,0,COMMAND_LEN);
    
    while ((bytes_written < byteCount) && (bytes_written < COMMAND_LEN))
    { 
        char c;
        if (get_user(c,buf+bytes_written + *byte_offset))
            return -EFAULT;
        command_buffer[bytes_written++] = c;
    }
    *byte_offset += bytes_written;

    pr_info(DRIVER_NAME "Command sent: %s (%d)",command_buffer, (int)bytes_written);

    __u8 reqlen = 8; 
    __u8 * data = kzalloc(reqlen,GFP_KERNEL);
    if (!data) { 
       return -ENOMEM; 
    } 
    memset(data,0,reqlen);
  
    __u8 endpoint      = 0x82; 
    __u8 requesttype   = 0; 
    __u8 request       = 0; 
    __u16 requestvalue = 7; 
    __u16 requestindex = 0x0102; 
    __u16 timeout      = 32; 


    __u16 pipe = usb_sndctrlpipe(my_usb_device->dev, endpoint);

    usb_control_msg(my_usb_device->dev,
                    pipe,
                    requesttype,
                    request,
                    requestvalue, 
                    requestindex,
                    data,
                    reqlen,
                    timeout);
  
    kfree(data); 

    return bytes_written;

}

//
// This is for the character device.
//

static const struct file_operations my_cdev_fops = {
	.owner          = THIS_MODULE,
	.write          = char_file_write,
	.read           = char_file_read,
	.open           = char_file_open,
	.release        = char_file_close,
};

int setup_char_driver(my_usb_device_t * my_usb_device) {

   int minor;

   spin_lock(&my_usb_driver->lock);
   minor = find_first_zero_bit(&my_usb_driver->minor_map, 8);
   if (minor >= 8) {
       spin_unlock(&my_usb_driver->lock);
       pr_err(DRIVER_NAME "Too many devices");
       return -ENODEV;
   }
   set_bit(minor, &my_usb_driver->minor_map);
   spin_unlock(&my_usb_driver->lock);

   my_usb_device->char_minor_device = minor;

   // Now create the actual minor device and entry in /dev. 
   pr_info(DRIVER_NAME "Creating device simpleusb%d", minor);

   my_usb_device->my_char_device = device_create(
                        my_usb_driver->my_class,
                        NULL, MKDEV(my_usb_driver->major_number, minor), my_usb_device, "simpleusb%d", minor);

   if (IS_ERR(my_usb_device->my_char_device)) {
        pr_info(DRIVER_NAME "Failed to create device\n");
        spin_lock(&my_usb_driver->lock);
        clear_bit(minor, &my_usb_driver->minor_map);
        spin_unlock(&my_usb_driver->lock);
        return PTR_ERR(my_usb_device->my_char_device);
   }

   return 0;

} 

void destroy_char_driver(my_usb_device_t * my_usb_device) 
{

   if (my_usb_device->my_char_device)
       device_destroy(my_usb_driver->my_class, MKDEV(my_usb_driver->major_number, my_usb_device->char_minor_device));

   spin_lock(&my_usb_driver->lock);
   clear_bit(my_usb_device->char_minor_device, &my_usb_driver->minor_map);
   list_del(&my_usb_device->node);
   spin_unlock(&my_usb_driver->lock);

   kfree(my_usb_device); 

}

static void my_usb_disconnect(struct usb_interface *interface)
{
    my_usb_device_t *my_usb_device = usb_get_intfdata(interface);
    if (my_usb_device)
        destroy_char_driver(my_usb_device);
    usb_set_intfdata(interface, NULL);
}

static struct usb_driver skel_driver = {
        .name        = DRIVER_NAME,
        .probe       = my_usb_probe,
        .disconnect  = my_usb_disconnect,
        .suspend     = NULL,
        .resume      = NULL,
        .pre_reset   = NULL,
        .post_reset  = NULL,
        .id_table    = my_usb_table,
        .supports_autosuspend = 1,
};




static int __init my_module_init(void)
{
    int result;

    my_usb_driver = kzalloc(sizeof(my_usb_driver_t), GFP_KERNEL);
    if (my_usb_driver == NULL)
    {
       pr_err(DRIVER_NAME "myusb allocation error");  
       return -ENOMEM; 
    } 

    spin_lock_init(&my_usb_driver->lock);
    INIT_LIST_HEAD(&my_usb_driver->my_usb_devices_list);
    my_usb_driver->minor_map = 0;

    my_usb_driver->major_number = register_chrdev(0, DEVICE_NAME, &my_cdev_fops);
    if (my_usb_driver->major_number < 0)
    {
        pr_err("Failed to register char device");
        result = my_usb_driver->major_number;
        goto err_free_driver;
    }

    my_usb_driver->my_class = class_create(DEVICE_NAME);
    if (IS_ERR(my_usb_driver->my_class))
    {
        pr_err(DRIVER_NAME "Failed to create class");
        result = PTR_ERR(my_usb_driver->my_class);
        goto err_unregister_chrdev;
    }

    result = usb_register(&skel_driver);
    if (result < 0) {
        pr_err("usb_register failed. Error number %d\n", result);
        goto err_destroy_class;
    }


    pr_info(DRIVER_NAME "USBModule: my_module_init done"); 
    return 0; 

err_destroy_class:
    class_destroy(my_usb_driver->my_class);
err_unregister_chrdev:
    unregister_chrdev(my_usb_driver->major_number, DEVICE_NAME);
err_free_driver:
    kfree(my_usb_driver);
    return result;
}

static void __exit my_module_exit(void)
{
   usb_deregister(&skel_driver);

   if (my_usb_driver) {
       if (my_usb_driver->my_class)
           class_destroy(my_usb_driver->my_class);
       if (my_usb_driver->major_number >= 0)
           unregister_chrdev(my_usb_driver->major_number, DEVICE_NAME);
       kfree(my_usb_driver);
   }
}

module_init(my_module_init);
module_exit(my_module_exit);

MODULE_LICENSE("GPL");
MODULE_AUTHOR("Roger Pease");
MODULE_DESCRIPTION("Roger's General Kernel Module");
